version: "3.5"

service:
  rest:
    container_name: rest
    build: .
    # ports:
    #   -
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
      - "27018:27018"
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGODB_USER: root
      MONGODB_DATABASE: rest
      MONGODB_PASS: root
    # volumes:
    #   - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
